name: Blog do Eckel
description: Blogging sobre tecnologias
meta_description: "Blog do Eckel"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://eckelp.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Gabriel Eckel Pelegrina"

# Disqus config
disqus-shortname: ""
